CREATE TABLE `pm_project` (
  `project_id` bigint NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  `project_code` varchar(50) NOT NULL COMMENT '项目编号(格式:行业-区域-简称-年份)',
  `project_name` varchar(200) NOT NULL COMMENT '项目名称',
  `project_full_name` varchar(500) DEFAULT NULL COMMENT '项目全称',
  `industry` varchar(50) DEFAULT NULL COMMENT '行业 字典表 字典类型industry',
  `region` varchar(50) DEFAULT NULL COMMENT '区域 字典表 字典类型sys_yjqy',
  `short_name` varchar(50) DEFAULT NULL COMMENT '简称',
  `year` int DEFAULT NULL COMMENT '年份',
  `project_category` varchar(50) DEFAULT NULL COMMENT '项目分类(字典表 字典类型sys_xmfl)',
  `project_dept` varchar(100) DEFAULT NULL COMMENT '项目部门',
  `project_status` varchar(50) DEFAULT NULL COMMENT '项目阶段(字典表 字典类型sys_xmjd)',
  `acceptance_status` varchar(50) DEFAULT NULL COMMENT '验收状态(字典表 字典类型sys_yszt)',
  `estimated_workload` decimal(10,2) DEFAULT NULL COMMENT '预估工作量(人天)',
  `actual_workload` decimal(10,2) DEFAULT '0.00' COMMENT '实际工作量(人天)',
  `project_address` varchar(500) DEFAULT NULL COMMENT '项目地址',
  `project_plan` text COMMENT '项目计划',
  `project_description` text COMMENT '项目描述',
  `project_manager_id` bigint DEFAULT NULL COMMENT '项目经理ID',
  `market_manager_id` bigint DEFAULT NULL COMMENT '市场经理ID',
  `participants` varchar(500) DEFAULT NULL COMMENT '参与人员ID列表(逗号分隔)',
  `sales_manager_id` bigint DEFAULT NULL COMMENT '销售负责人ID',
  `sales_contact` varchar(50) DEFAULT NULL COMMENT '销售联系方式',
  `team_leader_id` bigint DEFAULT NULL COMMENT '团队负责人ID',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_contact_id` bigint DEFAULT NULL COMMENT '客户联系人ID',
  `merchant_contact` varchar(100) DEFAULT NULL COMMENT '商户联系人',
  `merchant_phone` varchar(50) DEFAULT NULL COMMENT '商户联系方式',
  `start_date` date DEFAULT NULL COMMENT '启动日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `production_date` date DEFAULT NULL COMMENT '投产日期',
  `acceptance_date` date DEFAULT NULL COMMENT '验收日期',
  `implementation_year` varchar(10) DEFAULT NULL COMMENT '实施年度',
  `project_budget` decimal(15,2) DEFAULT NULL COMMENT '项目预算(元)',
  `project_cost` decimal(15,2) DEFAULT NULL COMMENT '项目费用(元)',
  `cost_budget` decimal(15,2) DEFAULT NULL COMMENT '费用预算(元)',
  `budget_cost` decimal(15,2) DEFAULT NULL COMMENT '成本预算(元)',
  `labor_cost` decimal(15,2) DEFAULT NULL COMMENT '人力费用(元)',
  `purchase_cost` decimal(15,2) DEFAULT '0.00' COMMENT '采购成本',
  `approval_status` varchar(20) DEFAULT NULL COMMENT '审批状态(待审核/已通过/已拒绝)',
  `approval_reason` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `industry_code` varchar(50) DEFAULT NULL COMMENT '行业代码',
  `region_code` varchar(50) DEFAULT NULL COMMENT '区域代码(字典:sys_yjqy)',
  `approval_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approver_id` varchar(64) DEFAULT NULL COMMENT '审批人',
  `remark` text COMMENT '备注',
  `reserved_field1` varchar(64) DEFAULT NULL COMMENT '备用域1',
  `reserved_field2` varchar(64) DEFAULT NULL COMMENT '备用域2',
  `reserved_field3` varchar(64) DEFAULT NULL COMMENT '备用域3',
  `reserved_field4` varchar(64) DEFAULT NULL COMMENT '备用域4',
  `reserved_field5` varchar(64) DEFAULT NULL COMMENT '备用域5',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 1删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`project_id`),
  UNIQUE KEY `uk_project_code` (`project_code`),
  KEY `idx_approval_status` (`approval_status`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目管理表';
CREATE TABLE `pm_project_approval` (
  `approval_id` bigint NOT NULL AUTO_INCREMENT COMMENT '审核主键ID',
  `project_id` bigint NOT NULL COMMENT '项目ID',
  `approval_status` varchar(50) NOT NULL DEFAULT '待审核' COMMENT '审核状态(0-待审核、1-通过、2-不通过)',
  `approval_reason` text COMMENT '审核原因/意见',
  `approver_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `approval_time` datetime DEFAULT NULL COMMENT '审核时间',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 1删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`approval_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_approval_status` (`approval_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目审核表';
CREATE TABLE `pm_contract` (
  `contract_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '合同主键ID',
  `contract_code` varchar(100) DEFAULT NULL COMMENT '合同编号',
  `contract_name` varchar(200) NOT NULL COMMENT '合同名称',
  `customer_id` bigint(20) NOT NULL COMMENT '关联客户ID',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
  `contract_type` varchar(50) NOT NULL COMMENT '合同类型(字典:sys_htlx)',
  `contract_status` varchar(50) DEFAULT '未签署' COMMENT '合同状态(字典:sys_htzt)',
  `contract_sign_date` date DEFAULT NULL COMMENT '合同签订日期',
  `contract_period` int(11) DEFAULT NULL COMMENT '合同周期(月)',
  `contract_amount` decimal(15,2) NOT NULL COMMENT '合同金额(含税)',
  `tax_rate` decimal(5,2) DEFAULT NULL COMMENT '税率(%)',
  `amount_no_tax` decimal(15,2) DEFAULT NULL COMMENT '不含税金额',
  `tax_amount` decimal(15,2) DEFAULT NULL COMMENT '税金',
  `confirm_amount` decimal(15,2) DEFAULT 0.00 COMMENT '合同确认金额',
  `confirm_year` varchar(10) DEFAULT NULL COMMENT '确认年份(字典:sys_ndgl)',
  `free_maintenance_period` int(11) DEFAULT NULL COMMENT '免维期(月)',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 1删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `reserved_field1` varchar(64) DEFAULT NULL COMMENT '备用域1',
  `reserved_field2` varchar(64) DEFAULT NULL COMMENT '备用域2',
  `reserved_field3` varchar(64) DEFAULT NULL COMMENT '备用域3',
  `reserved_field4` varchar(64) DEFAULT NULL COMMENT '备用域4',
  `reserved_field5` varchar(64) DEFAULT NULL COMMENT '备用域5',
  PRIMARY KEY (`contract_id`),
  UNIQUE KEY `uk_contract_code` (`contract_code`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_contract_status` (`contract_status`),
  KEY `idx_contract_sign_date` (`contract_sign_date`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同管理表';
CREATE TABLE `pm_attachment` (
  `attachment_id` bigint NOT NULL AUTO_INCREMENT COMMENT '附件主键ID',
  `file_name` varchar(255) NOT NULL COMMENT '文件名称',
  `file_original_name` varchar(255) NOT NULL COMMENT '文件原始名称',
  `file_path` varchar(500) NOT NULL COMMENT '文件存储路径',
  `file_size` bigint NOT NULL COMMENT '文件大小(字节)',
  `file_type` varchar(50) NOT NULL COMMENT '文件类型(扩展名)',
  `file_url` varchar(500) DEFAULT NULL COMMENT '文件访问URL',
  `business_type` varchar(50) NOT NULL COMMENT '业务类型(contract-合同,project-项目,payment-款项)',
  `business_id` bigint NOT NULL COMMENT '业务ID',
  `document_type` varchar(50) DEFAULT NULL COMMENT '文档类型(字典:sys_wdlx)',
  `upload_user_id` bigint DEFAULT NULL COMMENT '上传人ID',
  `upload_user_name` varchar(100) DEFAULT NULL COMMENT '上传人姓名',
  `download_count` int DEFAULT 0 COMMENT '下载次数',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 1删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`attachment_id`),
  KEY `idx_business` (`business_type`, `business_id`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附件管理表';
create table pm_project_contract_rel(
  rel_id        bigint auto_increment comment '关系主键ID'
  project_id    varchar(50)                           not null comment '项目ID',
  contract_id   bigint                                not null comment '合同ID',
  rel_status    varchar(50) default '有效'            null comment '关系状态(有效、失效)',
  bind_date     date                                  null comment '关联日期',
  del_flag      char        default '0'               null comment '删除标志(0正常 1删除)',
  create_by     varchar(64)                           null comment '创建者',
  create_time   datetime    default CURRENT_TIMESTAMP null comment '创建时间',
  update_by     varchar(64)                           null comment '更新者',
  update_time   datetime    default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP comment '更新时间',
  remark        varchar(500)                          null comment '备注',
  constraint uk_project_contract
  unique (project_id, contract_id, del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目合同关系表';
CREATE TABLE `pm_attachment_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '日志主键ID',
  `attachment_id` bigint NOT NULL COMMENT '附件ID',
  `file_original_name` varchar(255) DEFAULT NULL COMMENT '文件原始名称',
  `business_type` varchar(50) DEFAULT NULL COMMENT '业务类型(contract-合同,project-项目,payment-款项)',
  `business_id` bigint DEFAULT NULL COMMENT '业务ID',
  `document_type` varchar(50) DEFAULT NULL COMMENT '文档类型(字典:sys_wdlx)',
  `operation_type` varchar(50) NOT NULL COMMENT '操作类型(upload-上传,download-下载,delete-删除,view-查看)',
  `operation_desc` varchar(500) DEFAULT NULL COMMENT '操作描述',
  `operation_user_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operation_user_name` varchar(100) DEFAULT NULL COMMENT '操作人姓名',
  `operation_ip` varchar(50) DEFAULT NULL COMMENT '操作IP',
  `operation_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`log_id`),
  KEY `idx_attachment_id` (`attachment_id`),
  KEY `idx_business` (`business_type`, `business_id`),
  KEY `idx_operation_time` (`operation_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附件操作日志表';
